#-------------------------------------------------------------------------------
# Name:        breakBeats
# Purpose:     A SoundCloud-integrated music store simulation.
# Author:      Kenta Iwasaki
# Created:     08/03/2014
# Copyright:   (c) Kenta Iwasaki 2014
#-------------------------------------------------------------------------------

# PyQT Framework Module Imports
from PyQt5 import QtCore, QtGui, QtWidgets

# A layout container for the Main Window's context.
class Ui_MainWindow(object):
    # Initiates and defines all the GUI elements along with their properties.
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 590)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 590))
        MainWindow.setMaximumSize(QtCore.QSize(800, 590))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.storeList = QtWidgets.QTableWidget(self.centralwidget)
        self.storeList.setGeometry(QtCore.QRect(270, 70, 521, 481))
        self.storeList.setMaximumSize(QtCore.QSize(561, 16777215))
        self.storeList.setAcceptDrops(False)
        self.storeList.setAutoFillBackground(False)
        self.storeList.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.storeList.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.storeList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.storeList.setShowGrid(True)
        self.storeList.setCornerButtonEnabled(False)
        self.storeList.setObjectName("storeList")
        self.storeList.setColumnCount(4)
        self.storeList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.storeList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.storeList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.storeList.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.storeList.setHorizontalHeaderItem(3, item)
        self.storeList.horizontalHeader().setStretchLastSection(True)
        self.storeList.verticalHeader().setCascadingSectionResizes(False)
        self.storeList.verticalHeader().setStretchLastSection(False)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 781, 54))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btnBuy = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnBuy.setObjectName("btnBuy")
        self.gridLayout.addWidget(self.btnBuy, 3, 6, 1, 1)
        self.audioPosition = QtWidgets.QLabel(self.gridLayoutWidget)
        self.audioPosition.setAlignment(QtCore.Qt.AlignCenter)
        self.audioPosition.setObjectName("audioPosition")
        self.gridLayout.addWidget(self.audioPosition, 4, 6, 1, 1)
        self.seekSlider = QtWidgets.QSlider(self.gridLayoutWidget)
        self.seekSlider.setProperty("value", 0)
        self.seekSlider.setOrientation(QtCore.Qt.Horizontal)
        self.seekSlider.setObjectName("seekSlider")
        self.gridLayout.addWidget(self.seekSlider, 4, 5, 1, 1)
        self.btnPause = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnPause.setObjectName("btnPause")
        self.gridLayout.addWidget(self.btnPause, 4, 2, 1, 1)
        self.songName = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.songName.setFont(font)
        self.songName.setAlignment(QtCore.Qt.AlignCenter)
        self.songName.setObjectName("songName")
        self.gridLayout.addWidget(self.songName, 3, 5, 1, 1)
        self.btnStop = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnStop.setObjectName("btnStop")
        self.gridLayout.addWidget(self.btnStop, 4, 3, 1, 1)
        self.balanceLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.balanceLabel.setFont(font)
        self.balanceLabel.setScaledContents(False)
        self.balanceLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.balanceLabel.setObjectName("balanceLabel")
        self.gridLayout.addWidget(self.balanceLabel, 3, 0, 1, 2)
        self.cashLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cashLabel.setObjectName("cashLabel")
        self.gridLayout.addWidget(self.cashLabel, 3, 2, 1, 1)
        self.btnPlay = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnPlay.setObjectName("btnPlay")
        self.gridLayout.addWidget(self.btnPlay, 4, 0, 1, 2)
        self.btnShuffle = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnShuffle.setObjectName("btnShuffle")
        self.gridLayout.addWidget(self.btnShuffle, 4, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 3, 1, 2)
        self.songImage = QtWidgets.QGraphicsView(self.centralwidget)
        self.songImage.setGeometry(QtCore.QRect(10, 70, 251, 251))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.songImage.sizePolicy().hasHeightForWidth())
        self.songImage.setSizePolicy(sizePolicy)
        self.songImage.setSceneRect(QtCore.QRectF(0.0, 0.0, 0.0, 0.0))
        self.songImage.setObjectName("songImage")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 330, 251, 170))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnProfile = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnProfile.setObjectName("btnProfile")
        self.verticalLayout.addWidget(self.btnProfile)
        self.btnPurchaseHistory = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnPurchaseHistory.setObjectName("btnPurchaseHistory")
        self.verticalLayout.addWidget(self.btnPurchaseHistory)
        self.btnFund = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnFund.setObjectName("btnFund")
        self.verticalLayout.addWidget(self.btnFund)
        self.btnHistory = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnHistory.setObjectName("btnHistory")
        self.verticalLayout.addWidget(self.btnHistory)
        self.btnCheckout = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnCheckout.setFont(font)
        self.btnCheckout.setObjectName("btnCheckout")
        self.verticalLayout.addWidget(self.btnCheckout)
        self.btnManager = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnManager.setObjectName("btnManager")
        self.verticalLayout.addWidget(self.btnManager)
        self.historyList = QtWidgets.QTableWidget(self.centralwidget)
        self.historyList.setGeometry(QtCore.QRect(270, 70, 521, 481))
        self.historyList.setMaximumSize(QtCore.QSize(561, 16777215))
        self.historyList.setAcceptDrops(False)
        self.historyList.setAutoFillBackground(False)
        self.historyList.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.historyList.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.historyList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.historyList.setShowGrid(True)
        self.historyList.setCornerButtonEnabled(False)
        self.historyList.setObjectName("historyList")
        self.historyList.setColumnCount(4)
        self.historyList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.historyList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.historyList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.historyList.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.historyList.setHorizontalHeaderItem(3, item)
        self.historyList.horizontalHeader().setStretchLastSection(True)
        self.historyList.verticalHeader().setCascadingSectionResizes(False)
        self.historyList.verticalHeader().setStretchLastSection(False)
        self.btnClearHistory = QtWidgets.QPushButton(self.centralwidget)
        self.btnClearHistory.setGeometry(QtCore.QRect(644, 560, 141, 23))
        self.btnClearHistory.setObjectName("btnClearHistory")
        self.trackCount = QtWidgets.QLabel(self.centralwidget)
        self.trackCount.setGeometry(QtCore.QRect(10, 560, 251, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.trackCount.setFont(font)
        self.trackCount.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.trackCount.setObjectName("trackCount")
        self.btnRefreshStore = QtWidgets.QPushButton(self.centralwidget)
        self.btnRefreshStore.setGeometry(QtCore.QRect(644, 560, 141, 23))
        self.btnRefreshStore.setObjectName("btnRefreshStore")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 520, 251, 31))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnLogout = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnLogout.setObjectName("btnLogout")
        self.verticalLayout_2.addWidget(self.btnLogout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # Set's string constant values for the UI elements.
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "breakBeats :: ICS4U Kenta Iwasaki"))
        self.storeList.setSortingEnabled(True)
        item = self.storeList.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Title"))
        item = self.storeList.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Duration"))
        item = self.storeList.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Artist"))
        item = self.storeList.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Price"))
        self.btnBuy.setText(_translate("MainWindow", "Add To Cart"))
        self.audioPosition.setText(_translate("MainWindow", "00:00:00"))
        self.btnPause.setText(_translate("MainWindow", "Pause"))
        self.songName.setText(_translate("MainWindow", "No track is currently playing."))
        self.btnStop.setText(_translate("MainWindow", "Stop"))
        self.balanceLabel.setText(_translate("MainWindow", "Balance:"))
        self.cashLabel.setText(_translate("MainWindow", "$0"))
        self.btnPlay.setText(_translate("MainWindow", "Play"))
        self.btnShuffle.setText(_translate("MainWindow", "Shuffle"))
        self.label.setText(_translate("MainWindow", "Currently Playing:"))
        self.btnProfile.setText(_translate("MainWindow", "Profile Information"))
        self.btnPurchaseHistory.setText(_translate("MainWindow", "Purchase History"))
        self.btnFund.setText(_translate("MainWindow", "Fund Account"))
        self.btnHistory.setText(_translate("MainWindow", "Play History"))
        self.btnCheckout.setText(_translate("MainWindow", "Store Checkout"))
        self.btnManager.setText(_translate("MainWindow", "Manager Panel"))
        item = self.historyList.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Title"))
        item = self.historyList.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Duration"))
        item = self.historyList.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Artist"))
        item = self.historyList.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Price"))
        self.btnClearHistory.setText(_translate("MainWindow", "Clear History"))
        self.trackCount.setText(_translate("MainWindow", "There are currently 0 tracks in stock."))
        self.btnRefreshStore.setText(_translate("MainWindow", "Refresh Store List"))
        self.btnLogout.setText(_translate("MainWindow", "Logout"))

